#pragma once

enum class Error
{
	NONE,
	UNKNOWN_SYMBOL,
	INVALID_NUMBER,
	STRING_LITERAL_INCOMPLETE,
	EMPTY_INPUT,
	INVALID_ID,
	INVALID_EXP,
	TERM_EXPECTED,
	PARAN_CLOSE_EXPECTED,
	BRACKET_CLOSE_EXPECTED,
};	