#pragma once

enum class Error
{
	NONE,
	UNKNOWN_SYMBOL,
	INVALID_NUMBER,
	STRING_LITERAL_INCOMPLETE,
	EMPTY_INPUT,
	INVALID_ID,
	EXP_EXPECTED,
	INVALID_RELATION,
	TERM_EXPECTED,
	PARAN_CLOSE_EXPECTED,
	BRACKET_CLOSE_EXPECTED,
};	